# Generated by Django 2.2.17 on 2020-12-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransferreport',
            old_name='receiver_name',
            new_name='received_label',
        ),
        migrations.RenameField(
            model_name='accounttransferreport',
            old_name='sender_name',
            new_name='sended_label',
        ),
    ]
