# Generated by Django 2.2.17 on 2020-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201222_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
