# Generated by Django 3.1.4 on 2020-12-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransferreport',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
